apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: tasks
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]

---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: tasks
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
  namespace: tasks
spec:
  containers:
  - name: memory-demo-3-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "1000Gi"
      requests:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]


Comment : >
   Motivation for memory requests and limits
   a. By configuring memory requests and limits for the Containers that run in your cluster, you can make efficient use of the memory resources available on your cluster's Nodes. 
   b. By keeping a Pod's memory request low, you give the Pod a good chance of being scheduled. 
   c. By having a memory limit that is greater than the memory request, you accomplish two things:
      - The Pod can have bursts of activity where it makes use of memory that happens to be available.
      - The amount of memory a Pod can use during a burst is limited to some reasonable amount.
