# Specify a cpu request and a memory limit
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: tasks
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    command: ["stress"]
    args:
    - -cpus
    - "2"

---
# Specify a CPU request that is too big for your Nodes
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: tasks
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"


Comments : > 
  If you specify a CPU limit for a Container but do not specify a CPU request, 
  Kubernetes automatically assigns a CPU request that matches the limit. Similarly, 
  if a Container specifies its own memory limit, but does not specify a memory request, 
  Kubernetes automatically assigns a memory request that matches the limit.

