apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: tasks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: tasks
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pool-pnkmkikhl-8rk3j