# A Container's file system lives only as long as the Container does. 
# So when a Container terminates and restarts, filesystem changes are lost. 
# For more consistent storage that is independent of the Container, you can use a Volume. 
# This is especially important for stateful applications, such as key-value stores (such as Redis) and databases
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: tasks
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
